_target_: src.models.resnet_ivon_module.ResnetIVONLitModule

net_config:
  arch: resnet18
  in_channels: 3
  num_classes: 10
  dropout_rate: 0

train_samples: 1

test_samples: 5

lr: 0.1

scheduler: null

compile: false
