_target_: src.models.resnet_mcd_module.ResnetMCDLitModule

net_config:
  arch: resnet18
  dropout_rate: 0

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler: null

compile: false
# NOTE
# Every 1st indent parameter MUST be a parameter of the class _target_ on top
# If we need to pass an object as a parameter then we can instantiate it like `net` here
