# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/submitit/%j
timeout_min: 720
cpus_per_task: 16
gpus_per_node: null # Leave null
# If using ddp, this needs to be greater than or equal to the number of GPUs in each node
tasks_per_node: 1
mem_gb: 128
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
gres: "gpu:4"
setup:
  - module load cuda
  - source ~/miniconda3/etc/profile.d/conda.sh
  - conda activate devinterp_env
