_target_: torch.optim.lr_scheduler.CosineAnnealingLR
_partial_: true
T_max: 50 # Number of epochs to restart (should be <= total training epochs)
eta_min: 0.0 # Minimum learning rate

# no need of metric to be monitored
